Shop/Shop.Web/Models/ErrorViewModel.cs
using System;

namespace Shop.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Shop/Shop.Web/Controllers/AutentificationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;
using Shop.Web.Infrastructure;


namespace Shop.Web.Controllers
{
    public class AutentificationController : Controller
    {
        [HttpPost]
        public ActionResult Login(string userName, string password)
        {
            User user  = LoginRepository.GetUserByName(userName);

            if (user == null || user.Password.ToString() != password)
            {
                /*HttpContext.Session.Set("name", null);*/
                ViewBag.message = "Parola sau Nume incorect!";

                return View("Login");
            }
            else
            {
              
                HttpContext.Session.SetString("user", JsonConvert.SerializeObject(user));
                return RedirectToAction("Index", "Home");
              
            }
        }

        public ActionResult Login()
        {
            return View();
        }
       
    }
}

Shop/Shop.Web/Controllers/AuthenticationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;
using Shop.Web.Infrastructure;


namespace Shop.Web.Controllers
{
    public class AutentificationController : Controller
    {
        [HttpPost]
        public ActionResult Login(string userName, string password)
        {
            User user  = LoginRepository.GetUserByName(userName);

            if (user == null || user.Password.ToString() != password)
            {
                HttpContext.Session.Set("name", null);
				ViewBag.message = "Parola sau Nume incorect!";

                return View("Login");
            }
            else
            {
              
                HttpContext.Session.SetString("user", JsonConvert.SerializeObject(user));
                return RedirectToAction("Index", "Home");
              
            }
        }

        public ActionResult Login()
        {
            return View();
        }
       
    }
}

Shop/Shop.Web/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Shop.Web.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Shop/Shop.Web/Controllers/FAQController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Shop.Web.Controllers
{
    public class FAQController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Shop/Shop.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Shop.Web.Models;

namespace Shop.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
   

    }
}

Shop/Shop.Web/Controllers/MembershipController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Shop.Web.Infrastructure;

namespace Shop.Web.Controllers
{
    public class MembershipController : Controller
    {

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateCustomer(string forename, string surename, string address, string email, int phone, string password)
        {
            User user = new User { Name = forename, Surename = surename, Address = address, Email = email, Phone = phone, Password = password };

            LoginRepository.CreateCustomer(user);

            return RedirectToAction("Index");

        }
       /*   
        
        public ActionResult CreateUser(string username, string password )
        {
            User user = new User { Username = username,  Password = password};

            LoginRepository.CreateUser(user);


        }
        */
        
    }
}

Shop/Shop.Web/Controllers/PromosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Shop.Web.Controllers
{
    public class PromosController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Shop/Shop.Web/Controllers/ShopController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Domain;
using System.Data.SqlClient;

namespace Shop.Web.Controllers
{
    public class ShopController : Controller
    {



        public ActionResult Index(string sortby)
        {

            List<Product> products = new List<Product>();

            switch (sortby)
            {
                case "name-a-z":
                    products = Infrastructure.ShopSorter.SortByNameAZ();
                    break;
                case "name-z-a":
                    products = Infrastructure.ShopSorter.SortByNameZA();
                    break;
                case "price-l-h":
                    products = Infrastructure.ShopSorter.PriceL2H();
                    break;
                case "price-h-l":
                    products = Infrastructure.ShopSorter.PriceH2L();
                    break;

                default:
                    products = Infrastructure.ShopSorter.GetProducts();
                    break;

            }
            return View(products);


        }

        public ActionResult SingleShop(int id)
        {

            ViewBag.Message = "SingleShop";
            Product product = Infrastructure.ShopSorter.ShowItem(id);
            return View(product);

        }


        //public ActionResult CategoryModel(string Model)
        //{
        //    List<Product> products = new List<Product>();
        //    products = Infrastructure.ShopSorter.CategoryModel(Model);
        //    return View(products);
        //}

        public ActionResult CategoryBrand(string sortby)
        {
            List<Product> products = new List<Product>();

            switch (sortby)
            {
                case "BrandTest":
                    products = Infrastructure.ShopSorter.CategoryBrand(sortby);
                    break;
                case "BrandTest2":
                    products = Infrastructure.ShopSorter.CategoryBrand(sortby);
                    break;
                case "BrandTest3":
                    products = Infrastructure.ShopSorter.CategoryBrand(sortby);
                    break;
                default:
                    products = Infrastructure.ShopSorter.GetProducts();
                    break;

            }

            return View(products);
        }
        
    }
}

Shop/Shop.Web/Views/Autentification/Index.cshtml
@{
    ViewBag.Title = "Authentication";
}
<span>@ViewBag.message</span>

<form method="post" action="/Authentication/Login">
    <div class="form-group">
        <label for="exampleInputName">Name </label>
        <input type="text" class="form-control" name="userName" aria-describedby="NameHelp" placeholder="Enter Name">
        <small id="NameHelp" class="form-text text-muted">We'll never share your confidential data with anyone else.</small>
    </div>

    <div class="form-group">
        <label for="exampleInputPassword1">Password</label>
        <input type="password" class="form-control" name="password" placeholder="Password">
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>

Shop/Shop.Web/Views/Autentification/Login.cshtml
@{
    ViewBag.Title = "Autentification";
}
<span>@ViewBag.message</span>

<form method="post" action="/Autentification/Login">
    <div class="form-group">
        <label for="exampleInputName">Name </label>
        <input type="text" class="form-control" name="userName" aria-describedby="NameHelp" placeholder="Enter Name">
        <small id="NameHelp" class="form-text text-muted">We'll never share your confidential data with anyone else.</small>
    </div>

    <div class="form-group">
        <label for="exampleInputPassword1">Password</label>
        <input type="password" class="form-control" name="password" placeholder="Password">
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>

Shop/Shop.Web/Views/Authentication/Login.cshtml
@{
    ViewBag.Title = "Authentication";
}
<span>@ViewBag.message</span>

<form method="post" action="/Authentication/Login">
    <div class="form-group">
        <label for="exampleInputName">Name </label>
        <input type="text" class="form-control" name="userName" aria-describedby="NameHelp" placeholder="Enter Name">
        <small id="NameHelp" class="form-text text-muted">We'll never share your confidential data with anyone else.</small>
    </div>

    <div class="form-group">
        <label for="exampleInputPassword1">Password</label>
        <input type="password" class="form-control" name="password" placeholder="Password">
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>

Shop/Shop.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="site-blocks-cover" style="background-image: url(images/Principal.jpg);" data-aos="fade">
    <div class="container">
        <div class="row align-items-start align-items-md-center justify-content-end">
            <div class="col-md-5 text-center text-md-left pt-5 pt-md-0">
                <h1 style="color:#ff0000" class="mb-2">
                    Finding Your Perfect Appliance
                </h1>
                <div class="intro-text text-center text-md-left">
                    <p style="color:#ff0000" class="mb-4">Best quality vs price deals you can find. </p>
                    <p>
                        <a href="#" class="btn btn-sm btn-primary">Shop Now</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="site-section site-section-sm site-blocks-1">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-lg-4 d-lg-flex mb-4 mb-lg-0 pl-4" data-aos="fade-up" data-aos-delay="">
                <div class="icon mr-4 align-self-start">
                    <span class="icon-truck"></span>
                </div>
                <div class="text">
                    <h2 class="text-uppercase">Free Shipping</h2>
                    <p>With our futuristic delivery system you will get free shipping anywhere.</p>
                </div>
            </div>
            <div class="col-md-6 col-lg-4 d-lg-flex mb-4 mb-lg-0 pl-4" data-aos="fade-up" data-aos-delay="100">
                <div class="icon mr-4 align-self-start">
                    <span class="icon-refresh2"></span>
                </div>
                <div class="text">
                    <h2 class="text-uppercase">Free Returns</h2>
                    <p>If you don't like it, you can send it back for free.</p>
                </div>
            </div>
            <div class="col-md-6 col-lg-4 d-lg-flex mb-4 mb-lg-0 pl-4" data-aos="fade-up" data-aos-delay="200">
                <div class="icon mr-4 align-self-start">
                    <span class="icon-help"></span>
                </div>
                <div class="text">
                    <h2 class="text-uppercase">Customer Support</h2>
                    <p>If you have any questions, our customer care specialists are at a phone call away from you.</p>
                </div>
            </div>
        </div>
    </div>
</div>

<!DOCTYPE html>
<html>
<body text="black">

    <h1>About us!</h1>
    <p>
        QAppliances is an online retail service based in Romania. Launched in 2010, it is made up of small businesses in Romania and other locations,
        such as Singapore, that offer products to international online buyers. It is the most visited e-commerce website in Russia and was the 10th
        most popular website in Brazil.
    </p>

    <p>
        It facilitates small businesses to sell to customers all over the world, and one can find almost anything for sale.
        \It is more accurately compared to eBay, as sellers are independent, using QAppliances as a host to sell to consumers and other businesses.
    </p>
    @* <p><a href="https://www.w3schools.com">Visit W3Schools.com!</a></p>

        <p>The text attribute is not supported in HTML5. Use CSS instead.</p>*@

    <li>@Html.ActionLink("F.A.Q.", "Index", "FAQ")</li>

</body>
</html>

@*@<div class="site-section site-blocks-2">
        <div class="container">
            <div class="row">
                <div class="col-sm-6 col-md-6 col-lg-4 mb-4 mb-lg-0" data-aos="fade" data-aos-delay="">
                    <a class="block-2-item" href="#">
                        <figure class="image">
                            <img src="images/women.jpg" alt="" class="img-fluid">
                        </figure>
                        <div class="text">
                            <!--<span class="text-uppercase">Collections</span>-->
                            <h3>Laundry machines</h3>
                        </div>
                    </a>
                </div>
                <div class="col-sm-6 col-md-6 col-lg-4 mb-5 mb-lg-0" data-aos="fade" data-aos-delay="100">
                    <a class="block-2-item" href="#">
                        <figure class="image">
                            <img src="images/children.jpg" alt="" class="img-fluid">
                        </figure>
                        <div class="text">
                            <!--<span class="text-uppercase">Collections</span>-->
                            <h3>Fridges</h3>
                        </div>
                    </a>
                </div>
                <div class="col-sm-6 col-md-6 col-lg-4 mb-5 mb-lg-0" data-aos="fade" data-aos-delay="200">
                    <a class="block-2-item" href="#">
                        <figure class="image">
                            <img src="images/men.jpg" alt="" class="img-fluid">
                        </figure>
                        <div class="text">
                            <!--<span class="text-uppercase">Collections</span>-->
                            <h3>Ironing machine</h3>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </div>*@

@*@ <div class="site-section block-3 site-blocks-2 bg-light">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-7 site-section-heading text-center pt-4">
                    <h2>Featured Products</h2>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="nonloop-block-3 owl-carousel">
                        <div class="item">
                            <div class="block-4 text-center">
                                <figure class="block-4-image">
                                    <img src="images/cloth_1.jpg" alt="Image placeholder" class="img-fluid">
                                </figure>
                                <div class="block-4-text p-4">
                                    <h3><a href="#">Tank Top</a></h3>
                                    <p class="mb-0">Finding perfect t-shirt</p>
                                    <p class="text-primary font-weight-bold">$50</p>
                                </div>
                            </div>
                        </div>
                        <div class="item">
                            <div class="block-4 text-center">
                                <figure class="block-4-image">
                                    <img src="images/shoe_1.jpg" alt="Image placeholder" class="img-fluid">
                                </figure>
                                <div class="block-4-text p-4">
                                    <h3><a href="#">Corater</a></h3>
                                    <p class="mb-0">Finding perfect products</p>
                                    <p class="text-primary font-weight-bold">$50</p>
                                </div>
                            </div>
                        </div>
                        <div class="item">
                            <div class="block-4 text-center">
                                <figure class="block-4-image">
                                    <img src="images/cloth_2.jpg" alt="Image placeholder" class="img-fluid">
                                </figure>
                                <div class="block-4-text p-4">
                                    <h3><a href="#">Polo Shirt</a></h3>
                                    <p class="mb-0">Finding perfect products</p>
                                    <p class="text-primary font-weight-bold">$50</p>
                                </div>
                            </div>
                        </div>
                        <div class="item">
                            <div class="block-4 text-center">
                                <figure class="block-4-image">
                                    <img src="images/cloth_3.jpg" alt="Image placeholder" class="img-fluid">
                                </figure>
                                <div class="block-4-text p-4">
                                    <h3><a href="#">T-Shirt Mockup</a></h3>
                                    <p class="mb-0">Finding perfect products</p>
                                    <p class="text-primary font-weight-bold">$50</p>
                                </div>
                            </div>
                        </div>
                        <div class="item">
                            <div class="block-4 text-center">
                                <figure class="block-4-image">
                                    <img src="images/shoe_1.jpg" alt="Image placeholder" class="img-fluid">
                                </figure>
                                <div class="block-4-text p-4">
                                    <h3><a href="#">Corater</a></h3>
                                    <p class="mb-0">Finding perfect products</p>
                                    <p class="text-primary font-weight-bold">$50</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
*@



@section scripts
    {


}

Shop/Shop.Web/Views/Promos/Index.cshtml
@{
    ViewData["Title"] = "Promos";
}

<h1>Promos</h1>

Shop/Shop.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Shoppers &mdash; Colorlib e-Commerce Template</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Mukta:300,400,700">
    <link rel="stylesheet" href="fonts/icomoon/style.css">

    <link rel="stylesheet" href="~/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/magnific-popup.css">
    <link rel="stylesheet" href="~/css/jquery-ui.css">
    <link rel="stylesheet" href="~/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/css/owl.theme.default.min.css">


    <link rel="stylesheet" href="~/css/aos.css">

    <link rel="stylesheet" href="~/css/style.css">

</head>
<body>
    <header class="site-navbar" role="banner">
        <div class="site-navbar-top">
            <div class="container">
                <div class="row align-items-center">

                    <div class="col-6 col-md-4 order-2 order-md-1 site-search-icon text-left">
                        <form action="" class="site-block-top-search">
                            <span class="icon icon-search2"></span>
                            <input type="text" class="form-control border-0" placeholder="Search">
                        </form>
                    </div>

                    <div class="col-12 mb-3 mb-md-0 col-md-4 order-1 order-md-2 text-center">
                        <div class="site-logo">
                            <a href="Home" class="js-logo-clone">Shoppers</a>
                        </div>
                    </div>

                    <div class="col-6 col-md-4 order-3 order-md-3 text-right">
                        <div class="site-top-icons">
                            <ul>
                                <li>@Html.ActionLink("Login","Login","Autentification")</li>
                                <li><a href="#"><span class="icon icon-heart-o"></span></a></li>
                                <li>
                                    <a href="cart.html" class="site-cart">
                                        <span class="icon icon-shopping_cart"></span>
                                        <span class="count">2</span>
                                    </a>
                                </li>
                                <li class="d-inline-block d-md-none ml-md-0"><a href="#" class="site-menu-toggle js-menu-toggle"><span class="icon-menu"></span></a></li>
                            </ul>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <nav class="site-navigation text-right text-md-center" role="navigation">
            <div class="container">
                <ul class="site-menu js-clone-nav d-none d-md-block">

                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Shop", "Index", "Shop")</li>

                    <li>@Html.ActionLink("Promos", "Index", "Promos")</li>
                    <li>@Html.ActionLink("Membership", "Index", "Membership")</li>

                    <li>@Html.ActionLink("Contact", "Index", "Contact")</li>
                </ul>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="site-footer border-top">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 mb-5 mb-lg-0">
                    <div class="row">
                        <div class="col-md-12">
                            <h3 class="footer-heading mb-4">Navigations</h3>
                        </div>
                        <div class="col-md-6 col-lg-4">
                            <ul class="list-unstyled">
                                <li><a href="#">Sell online</a></li>
                                <li><a href="#">Features</a></li>
                                <li><a href="#">Shopping cart</a></li>
                                <li><a href="#">Store builder</a></li>
                            </ul>
                        </div>
                        <div class="col-md-6 col-lg-4">
                            <ul class="list-unstyled">
                                <li><a href="#">Mobile commerce</a></li>
                                <li><a href="#">Dropshipping</a></li>
                                <li><a href="#">Website development</a></li>
                            </ul>
                        </div>
                        <div class="col-md-6 col-lg-4">
                            <ul class="list-unstyled">
                                <li><a href="#">Point of sale</a></li>
                                <li><a href="#">Hardware</a></li>
                                <li><a href="#">Software</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-lg-3 mb-4 mb-lg-0">
                    <a href=" Promos">
                       
                        <h3 class="footer-heading mb-4">Promo</h3>
                        <a href="#" class="block-6">

                            <img src="~/images/FindPerfectAppliances.jpg" alt="Image placeholder" class="img-fluid rounded mb-4">
                            <h3 class="font-weight-light  mb-0">Finding Your Perfect Gadget</h3>
                        </a>
                        <p>Promo from  nuary 15 &mdash; 25, 2019</p>
                        </abbr>
                </div>
                <div class="col-md-6 col-lg-3">
                    <div class="block-5 mb-5">
                        <h3 class="footer-heading mb-4">Contact Info</h3>
                        <ul class="list-unstyled">
                            <li class="address">Romania , Ploiesti</li>
                            <li class="phone"><a href="tel://23923929210">+2 392 3929 210</a></li>
                            <li class="email">emailaddress@Appliances.com</li>
                        </ul>
                    </div>

                    <div class="block-7">
                        <form action="#" method="post">
                            <label for="email_subscribe" class="footer-heading">Subscribe</label>
                            <div class="form-group">
                                <input type="text" class="form-control py-4" id="email_subscribe" placeholder="Email">
                                <input type="submit" class="btn btn-sm btn-primary" value="Send">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="row pt-5 mt-5 text-center">
                <div class="col-md-12">
                    <p>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        Copyright &copy;
                        <script data-cfasync="false" src="/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script>
                        <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank" class="text-primary">Colorlib</a>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    </p>
                </div>

            </div>
        </div>
    </footer>


    <script src="~/js/jquery-3.3.1.min.js"></script>
    <script src="~/js/jquery-ui.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/owl.carousel.min.js"></script>
    <script src="~/js/jquery.magnific-popup.min.js"></script>
    <script src="~/js/aos.js"></script>

    <script src="~/js/main.js"></script>

    @RenderSection("scripts", false)
</body>
</html>

Shop/Shop.Web/Views/Shop/SingleShop.cshtml
@model Domain.Product
@{
    ViewBag.Title = "SingleShop";
}


<div class="site-section">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <img src="@Url.Content(Model.ImageRefPath)" alt="If this shows up, I screwed up." class="img-fluid">
            </div>

            <div class="col-md-6">
                <h2 class="text-black">@Model.Name.</h2>
                @*<h2> @Model.Id</h2>*@
                <p class="mb-4">@Model.Description</p>
                <p><strong class="text-primary h4">@Model.Price</strong></p>
                <p>@Model.Model</p>
                <p>@Model.Brand</p>
                <div class="mb-1 d-flex">
                    <label for="option-sm" class="d-flex mr-3 mb-3">
                        <span class="d-inline-block mr-2" style="top:-2px; position: relative;"><input type="radio" id="option-sm" name="shop-sizes"></span> <span class="d-inline-block text-black">Small</span>
                    </label>
                    <label for="option-md" class="d-flex mr-3 mb-3">
                        <span class="d-inline-block mr-2" style="top:-2px; position: relative;"><input type="radio" id="option-md" name="shop-sizes"></span> <span class="d-inline-block text-black">Medium</span>
                    </label>
                    <label for="option-lg" class="d-flex mr-3 mb-3">
                        <span class="d-inline-block mr-2" style="top:-2px; position: relative;"><input type="radio" id="option-lg" name="shop-sizes"></span> <span class="d-inline-block text-black">Large</span>
                    </label>
                    <label for="option-xl" class="d-flex mr-3 mb-3">
                        <span class="d-inline-block mr-2" style="top:-2px; position: relative;"><input type="radio" id="option-xl" name="shop-sizes"></span> <span class="d-inline-block text-black"> Extra Large</span>
                    </label>
                </div>
                <div class="mb-5">
                    <div class="input-group mb-3" style="max-width: 120px;">
                        <div class="input-group-prepend">
                            <button class="btn btn-outline-primary js-btn-minus" type="button">&minus;</button>
                        </div>
                        <input type="text" class="form-control text-center" value="1" placeholder="" aria-label="Example text with button addon" aria-describedby="button-addon1">
                        <div class="input-group-append">
                            <button class="btn btn-outline-primary js-btn-plus" type="button">&plus;</button>
                        </div>
                    </div>

                </div>
                <p><a href="#" class="buy-now btn btn-sm btn-primary">Add To Cart</a></p>

            </div>
        </div>
    </div>
</div>
@*<div class="row">
        @foreach (var product in Model)
        {

            <div class="col-md-12">
                <div class="nonloop-block-3 owl-carousel">
                    <div class="item">
                        <div class="block-4 text-center">
                            <figure class="block-4-image">
                                <img src="images/cloth_1.jpg" alt="Image placeholder" class="img-fluid">
                            </figure>
                            <div class="block-4-text p-4">
                                <h3>@Html.ActionLink(product.Name, "SingleShop", "Shop")</h3>
                                <p class="mb-0">@product.Description</p>
                                <p class="text-primary font-weight-bold">@product.Price</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            }

    </div>
*@